services:
  chronos:
    build: ../..
    container_name: "chronos-api"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASS_DEV}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_DEV}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - chronos-dev-network

  postgres:
    image: postgres:16.11-alpine3.23
    container_name: "chronos-db"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASS_DEV}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
    networks:
      - chronos-dev-network

volumes:
  postgres_dev_data:
    driver: local

networks:
  chronos-dev-network:
    driver: bridge